# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-02 00:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RadioStations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('radio_station_call_sign', models.CharField(blank=True, help_text='Enter the radio station call sign.', max_length=50)),
                ('radio_station_band', models.PositiveIntegerField(choices=[(0, 'AM'), (1, 'FM')], default=0)),
                ('radio_station_frequency', models.DecimalField(decimal_places=2, default=0, help_text='Enter the radio station frequency', max_digits=5)),
                ('city_of_license', models.CharField(blank=True, help_text='Enter the city of license', max_length=50)),
                ('radio_station_licensee', models.CharField(blank=True, help_text='Enter the radio station licensee.', max_length=50)),
                ('radio_station_format', models.CharField(blank=True, help_text='Enter the station format.', max_length=50)),
            ],
        ),
    ]
